M=input('type the length of dft =');
N=input('type the length of the sequence =');
u=ones(1,N);
U=fft(u,M);
t=0:1:N-1;
figure;
subplot(3,1,1);
stem(t,u);
title('Original time domain sequence');
ylabel('Amplitude');
xlabel('Time index n');
subplot(3,1,2);
K=0:1:M-1;
stem(K,abs(U));
title('Magnitude of dft samples');
xlabel('Frequency index K');
ylabel('Magnitude');
subplot(3,1,3);
stem(K,angle(U));
title ('Magnitude of dft samples');
xlabel('Frequency index K');
ylabel('Phase');
