clc;
clear all;
x=input('Input First Sequence=');
h=input('Input Second Sequence=');
n1=length(x); 
n2=length(h);
N=n1+n2-1;
x1=[x zeros(1,N-n1)];
x2=[h zeros(1,N-n2)];
a=fft(x, N);
b=fft(h, N);
c=a.*b;
disp('Output sequence');
disp(c)
d=ifft(c, N);
dn=0:N-1;
subplot(3,1,1);
stem(x);
title('First Sequence');
ylabel('Signal'); 
xlabel('Time');
subplot(3,1,2); 
stem(h);
title('Second Sequence');
ylabel('Signal');
xlabel('Time');
subplot(3,1,3);
stem(d);
title('Convolved Sequence - Vikash patel');
ylabel('Signal');
xlabel('Time');
